name: Nicole Dominguez
description: Nicole Dominguez | Product Designer | NYC + Beyond
url: http://nicoledominguez.com
markdown: redcarpet
highlighter: pygments
permalink: /:categories/:title
timezone: America/New_York
exclude: ['config.rb', 'README.md','gems','Gemfile','Guardfile', '.DS_Store']
include: ['.htaccess', '.htpasswd']

rdiscount:
    extensions: [smart]

sass:
    sass_dir: assets/stylesheets
    css_dir: assets/stylesheets
    output_style: compact
    line_comments: false
    

# Plugin: jekyll-assets
assets:
  sources:
    - assets/sass
    - assets/stylesheets
    - assets/images

  css_compressor: sass
  cachebust: hard
  cache: false
  gzip: [ text/css, application/javascript ]
